### ISSUE TITLE
This Is Virus

### ISSUE THREAD

**Issue by Absolut3** [drygdryg/geomac-webpage#1]
https://www.virustotal.com/gui/file/459e7a164538e3aefd9ecb07aaa590bc9eb175e4e23e715f57a4f51fd82e694d?nocache=1

**Comment by drygdryg** [comment]
It's not a virus. Please check the executable files separately.
But if you don't believe me, you can use the geomac bot in Telegram. It is free and open to everyone. https://t.me/geomacbot
